CREATE PROCEDURE [dbo].[spProgram_Create]
	@ProgramName NVARCHAR(100)
	
AS
BEGIN
     SET NOCOUNT ON;
	 BEGIN TRY
	 IF EXISTS(
	 SELECT 1 FROM [dbo].[Program] WHERE [ProgramName] = @ProgramName
	 )
	 BEGIN 
		 RAISERROR('Program already exists!',16,1);
		 RETURN;
	 END
	 --INSERT THE PROGRAM NAME --
	 INSERT INTO [dbo].[Program] ([ProgramName]) VALUES (@ProgramName);

	 --RETURN NEW PROGRAM ID--
	SELECT SCOPE_IDENTITY() AS NewProgramId
	END TRY
	BEGIN CATCH
	;THROW;
	END CATCH
END

---SUMMARY-------
--CREATE PROGRAM PROCEDURE---
--THIS PROCEDURE BASICALLY CREATES THE NEW PROGRAM 
--FIRST IS SET NOCOUNT ON THIS REMOVES THE RETURN OF THIS MANY ROWS AFFECTED
--THEN IT STARTS THE TRY BLOCK AND CHECK IF ANY OF THE DATA WHICH HAS SAME NAME AS PROGRAM EXIST ALREADY OR NOT  IF EXIST THEN IT THROWS ERROR
--ELSE IT CREATES THE NEW PROGRAM AND RETURNS THE NEWLY CREATED PROGRAM ID
