CREATE PROCEDURE [dbo].[spProgram_Delete]
	@ProgramId INT
	
AS
BEGIN
    SET NOCOUNT ON;
	BEGIN TRY
		BEGIN TRANSACTION;
		IF EXISTS(
		   SELECT 1 FROM [dbo].[Semester]
		   WHERE [ProgramId] = @ProgramId
		)
	    BEGIN
		    RAISERROR('Cannot delete program. Delete all semester fisrt!',16,1);
			RETURN
	    END

		
		--ELSE DELETE PROGRAM IF NO DEPENDENCIES
		
		DELETE FROM [dbo].[Program] WHERE [ProgramId] = @ProgramId;
		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
	      ROLLBACK TRANSACTION;
		  ;THROW;
    END CATCH
END;

---SUMMARY---
--HERE IT DELETS OR REMOVES THE PROGRAM RECORD 
--IN TRY BLOCK  TRANSACTION IS CREATED THEN IT CHECKS FOR ANY DEPENDENCIES OF THE PROGRAM IF EXIST THEN ERROR IS THOWN AND TRANSACTION IS ROLLED BACK
--ELSE PROGRAM IS REMOVED AND TRANSCTION I COMIITED 